'use client';

import { useLanguage } from '@/lib/i18n/LanguageContext';
import { getLegalTranslation } from '@/lib/i18n/legal-translations';
import { Button } from '@/components/ui/button';
import { useRouter } from 'next/navigation';
import { FileText, Check } from 'lucide-react';

export default function TermsOfServicePage() {
  const { language } = useLanguage();
  const router = useRouter();

  const t = (key: string) => getLegalTranslation(language, key as any);

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">
      {/* Header */}
      <div className="border-b bg-white/80 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <FileText className="w-6 h-6 text-blue-600" />
            <h1 className="text-2xl font-bold text-gray-900">
              {t('legal.terms_title')}
            </h1>
          </div>
          <Button
            variant="ghost"
            onClick={() => router.push('/')}
          >
            {t('legal.back_home')}
          </Button>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-6 py-12">
        {/* Dates */}
        <div className="text-sm text-gray-600 mb-8">
          <p><strong>{t('legal.effective_date')}:</strong> January 16, 2026</p>
          <p><strong>{t('legal.last_updated')}:</strong> January 16, 2026</p>
        </div>

        {/* Summary */}
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-6 mb-8">
          <h2 className="text-xl font-bold text-blue-900 mb-4">
            {t('terms.summary.title')}
          </h2>
          <ul className="space-y-2">
            {[1, 2, 3, 4, 5, 6, 7].map(i => (
              <li key={i} className="flex items-start gap-2">
                <Check className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
                <span className="text-sm text-blue-900">
                  {t(`terms.summary.point${i}`)}
                </span>
              </li>
            ))}
          </ul>
        </div>

        {/* Main Content */}
        <div className="prose prose-blue max-w-none">
          {/* Section 1 */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              {t('terms.section1.title')}
            </h2>
            <p className="text-gray-700">
              {t('terms.section1.content')}
            </p>
          </section>

          {/* Section 2 */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              {t('terms.section2.title')}
            </h2>
            <div className="text-gray-700 space-y-3">
              <p><strong>Service:</strong> Sanyla, a web-based platform for AI-powered social media campaign generation and automated publishing</p>
              <p><strong>User:</strong> Any individual or entity accessing or using the Service</p>
              <p><strong>Credits:</strong> Digital units purchased via Stripe used to generate AI content and campaigns</p>
              <p><strong>Campaign:</strong> A 7-day series of social media posts generated by AI</p>
              <p><strong>AI Content:</strong> Text, images, and captions generated by artificial intelligence</p>
              <p><strong>Stripe:</strong> Third-party payment processor used for all transactions</p>
            </div>
          </section>

          {/* Section 3 */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              {t('terms.section3.title')}
            </h2>
            <p className="text-gray-700">To use Sanyla, you must:</p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2">
              <li>Be at least 18 years of age or the age of majority in your jurisdiction</li>
              <li>Have the legal capacity to enter into binding contracts</li>
              <li>Provide accurate and complete registration information</li>
              <li>Not be prohibited from using the Service under applicable laws</li>
            </ul>
          </section>

          {/* Section 4 */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              {t('terms.section4.title')}
            </h2>
            <p className="text-gray-700 mb-3">Sanyla provides the following features:</p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2">
              <li><strong>AI Campaign Generation:</strong> Create 7-day social media campaigns using AI</li>
              <li><strong>Multilingual Support:</strong> Generate content in 17 languages</li>
              <li><strong>Auto-Publishing:</strong> Schedule and automatically publish posts to Instagram, Facebook, and LinkedIn</li>
              <li><strong>Performance Metrics:</strong> Collect engagement data from published posts</li>
              <li><strong>Content Optimization:</strong> Receive AI-suggested improvements based on performance data</li>
            </ul>
          </section>

          {/* Section 5 - Payments */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              {t('terms.section5.title')}
            </h2>
            <p className="text-gray-700 mb-4">
              Sanyla offers the following one-time credit purchases via Stripe:
            </p>
            <div className="bg-gray-50 border border-gray-200 rounded-lg p-6 space-y-3">
              <div className="flex items-center justify-between">
                <span className="font-semibold text-gray-900">{t('terms.credits.starter')}</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="font-semibold text-gray-900">{t('terms.credits.pro')}</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="font-semibold text-gray-900">{t('terms.credits.power')}</span>
              </div>
            </div>
            <div className="mt-4 space-y-2 text-gray-700">
              <p>• All payments are processed securely via Stripe Checkout</p>
              <p>• Prices are displayed in Euros (EUR) and are final</p>
              <p>• No recurring charges or subscriptions</p>
              <p>• Credits never expire</p>
              <p>• Sanyla does not store or have access to your credit card information</p>
            </div>
          </section>

          {/* Section 6 - Refund Policy */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              {t('terms.section6.title')}
            </h2>
            <p className="text-gray-700">
              Refunds are only available for unused credits within 14 days of purchase.
              See our full{' '}
              <button
                onClick={() => router.push('/refund-policy')}
                className="text-blue-600 hover:underline font-semibold"
              >
                Refund Policy
              </button>
              {' '}for complete details.
            </p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2 mt-3">
              <li>No refunds for credits already used to generate campaigns or rewrites</li>
              <li>Refund requests must be submitted via email within 14 days</li>
              <li>Refunds are processed manually and evaluated case-by-case</li>
              <li>No automatic refunds</li>
            </ul>
          </section>

          {/* Section 7 - User Responsibilities */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              {t('terms.section7.title')}
            </h2>
            <p className="text-gray-700 mb-3">You agree NOT to use the Service to:</p>
            <ul className="list-disc pl-6 text-gray-700 space-y-2">
              <li>Violate any local, national, or international law</li>
              <li>Infringe on intellectual property rights</li>
              <li>Generate harmful, illegal, defamatory, or discriminatory content</li>
              <li>Spam, harass, or deceive others</li>
              <li>Distribute malware or engage in fraudulent activities</li>
              <li>Attempt to reverse engineer, hack, or exploit the Service</li>
            </ul>
            <p className="text-gray-700 mt-4">
              You are solely responsible for the content you generate and publish.
              You should review all content before publishing.
            </p>
          </section>

          {/* Section 8 - AI Disclaimer */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              {t('terms.section8.title')}
            </h2>
            <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-6">
              <p className="text-gray-900 font-semibold mb-3">No Performance Guarantees:</p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>AI-generated content is provided "as is"</li>
                <li>We do not guarantee engagement, reach, conversions, or any specific results</li>
                <li>Campaign performance depends on many factors outside our control</li>
                <li>Content can be generated in 17 languages, but may contain errors</li>
                <li>You should verify accuracy, especially for professional or legal content</li>
              </ul>
            </div>
          </section>

          {/* Limitation of Liability */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              Limitation of Liability
            </h2>
            <div className="bg-red-50 border border-red-200 rounded-lg p-6">
              <p className="text-gray-900 font-semibold mb-3">IMPORTANT:</p>
              <p className="text-gray-700 mb-3">
                Sanyla is operated by an individual and is not a registered company or legal entity.
                This service is provided on a best-effort basis.
              </p>
              <p className="text-gray-700">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW: We are not liable for indirect, incidental,
                consequential, or punitive damages. Our total liability to you is limited to the
                amount you paid in the 12 months prior to the claim.
              </p>
            </div>
          </section>

          {/* Contact */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              Contact Information
            </h2>
            <p className="text-gray-700">
              {t('terms.contact.website')}
            </p>
          </section>

          {/* Footer Links */}
          <div className="mt-12 pt-8 border-t border-gray-200">
            <p className="text-sm text-gray-600 mb-4">Related Documents:</p>
            <div className="flex gap-4">
              <button
                onClick={() => router.push('/privacy-policy')}
                className="text-blue-600 hover:underline text-sm font-semibold"
              >
                Privacy Policy
              </button>
              <button
                onClick={() => router.push('/refund-policy')}
                className="text-blue-600 hover:underline text-sm font-semibold"
              >
                Refund Policy
              </button>
            </div>
          </div>

          {/* Acknowledgment */}
          <div className="mt-8 bg-gray-900 text-white rounded-lg p-6">
            <p className="text-sm">
              BY USING SANYLA, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS OF SERVICE.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
