import { Injectable, Logger } from '@nestjs/common';
import { Cron } from '@nestjs/schedule';
import { PrismaService } from '../prisma/prisma.service';
import { PerformanceClassifierService } from './performance-classifier.service';
import { OpenAiService } from '../ai/openai.service';

/**
 * Auto-Suggestion Cron Job
 * 
 * Runs 1x per day at 9 AM Vilnius time
 * Finds UNDERPERFORMING posts from last 48h
 * Auto-generates optimized DRAFT ContentItems
 * NO auto-publish (safe operation)
 */
@Injectable()
export class AutoOptimizationProcessor {
  private readonly logger = new Logger(AutoOptimizationProcessor.name);

  constructor(
    private prisma: PrismaService,
    private performanceClassifier: PerformanceClassifierService,
    private openAiService: OpenAiService
  ) {}

  /**
   * Daily cron: Auto-suggest optimizations for underperforming posts
   * Schedule: 9 AM every day (Vilnius timezone)
   */
  @Cron('0 9 * * *', {
    name: 'auto-optimize-underperforming',
    timeZone: 'Europe/Vilnius',
  })
  async autoSuggestOptimizations() {
    this.logger.log('🤖 Starting auto-optimization suggestion process...');

    try {
      const now = new Date();
      const fortyEightHoursAgo = new Date(now.getTime() - 48 * 60 * 60 * 1000);

      // Find POSTED jobs with metrics from last 48h
      const recentJobs = await this.prisma.scheduleJob.findMany({
        where: {
          status: 'POSTED',
          publishedAt: {
            gte: fortyEightHoursAgo,
          },
          platformPostId: { not: null },
        },
        include: {
          contentItem: true,
          metrics: {
            orderBy: { collectedAt: 'desc' },
            take: 1,
          },
        },
        orderBy: { publishedAt: 'desc' },
      });

      this.logger.log(`📊 Found ${recentJobs.length} recent posted jobs to analyze`);

      let optimizedCount = 0;
      let skippedCount = 0;
      let errorCount = 0;

      for (const job of recentJobs) {
        try {
          // Skip if no metrics yet
          if (!job.metrics || job.metrics.length === 0) {
            this.logger.debug(`⏭️  Skipping job ${job.id}: no metrics yet`);
            skippedCount++;
            continue;
          }

          const latestMetric = job.metrics[0];
          const classification = this.performanceClassifier.classify(
            latestMetric.engagementRate
          );

          // Only process UNDERPERFORMING posts
          if (classification.status !== 'UNDERPERFORMING') {
            this.logger.debug(
              `✅ Job ${job.id} performing well (${(classification.engagementRate * 100).toFixed(2)}%)`
            );
            skippedCount++;
            continue;
          }

          // Check if already optimized (avoid duplicates)
          const existingOptimization = await this.prisma.contentItem.findFirst({
            where: {
              metadata: {
                path: ['originalScheduleJobId'],
                equals: job.id,
              },
            },
          });

          if (existingOptimization) {
            this.logger.debug(`⏭️  Job ${job.id} already has optimization`);
            skippedCount++;
            continue;
          }

          // Extract caption
          const content = job.contentItem.content as any;
          const originalCaption = content.caption || content.text || '';

          if (!originalCaption) {
            this.logger.warn(`⚠️  Job ${job.id} has no caption, skipping`);
            skippedCount++;
            continue;
          }

          // Generate optimized version
          this.logger.log(
            `🔄 Optimizing job ${job.id} (engagement: ${(classification.engagementRate * 100).toFixed(2)}%)`
          );

          const { hook, cta } = await this.openAiService.rewriteUnderperformingPost(
            originalCaption,
            classification.engagementRate
          );

          // Create optimized ContentItem (DRAFT)
          const originalTitle = job.contentItem.title || 'Post';
          await this.prisma.contentItem.create({
            data: {
              type: 'POST',
              title: `${originalTitle} (Auto-Optimized)`,
              content: {
                ...content,
                caption: content.caption, // Keep original for reference
                optimized: {
                  hook,
                  cta,
                  originalEngagementRate: classification.engagementRate,
                  optimizedAt: new Date().toISOString(),
                  autoGenerated: true,
                },
              },
              metadata: {
                originalContentItemId: job.contentItem.id,
                originalScheduleJobId: job.id,
                optimizationReason: 'AUTO_UNDERPERFORMING',
                engagementRate: classification.engagementRate,
                threshold: classification.threshold,
              },
              projectId: job.contentItem.projectId,
            },
          });

          optimizedCount++;
          this.logger.log(`✅ Created optimization for job ${job.id}`);
        } catch (error) {
          errorCount++;
          const errorMessage = error instanceof Error ? error.message : String(error);
          this.logger.error(`❌ Failed to optimize job ${job.id}: ${errorMessage}`);
          // Continue processing other jobs (no fail-fast)
        }
      }

      this.logger.log(
        `🎯 Auto-optimization complete: ${optimizedCount} optimized, ${skippedCount} skipped, ${errorCount} errors`
      );
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      this.logger.error(`💥 Auto-optimization cron failed: ${errorMessage}`);
    }
  }
}
